export type MockData = {
    filmNames: string[];
    descriptions: string[];
    // postDate: Date;
    genres: string[];
    releaseDates: number[];
    ratings: number[];
    prevVideos: string[];
    videos: string[];
    actors: string[];
    directors: string[];
    durations: number[];
    // comments: number[];
    userNames: string[];
    emails: string[];
    avatarPaths?: string[];
    passwords: string[];
    posters: string[];
    backgroundImages: string[];
    backgroundColors: string[];
  };
